export const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;
export const UNAUTHORIZED_ERROR_STATUS_CODE = 401;
export const CONFLICT_STATUS_CODE = 409;
export const BAD_REQUEST_ERROR_STATUS_CODE = 400;
export const NOT_FOUND_ERROR_STATUS_CODE = 404;
export const EXPIRED_TOKEN_MS = 3600000 * 24 * 7;